include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AvalancheSpringBoard
AvalancheSpringBoard_FILES = AVSpringBoard.x ../Shared/AVThemeLibrary.m
AvalancheSpringBoard_CFLAGS = -fobjc-arc -Wall -Wno-deprecated-declarations
AvalancheSpringBoard_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
