include $(THEOS)/makefiles/common.mk

TWEAK_NAME = LumenBoardSpringBoard
LumenBoardSpringBoard_FILES = LMSpringBoard.x ../Shared/LMThemeLibrary.m
LumenBoardSpringBoard_CFLAGS = -fobjc-arc -Wall -Wno-deprecated-declarations
LumenBoardSpringBoard_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
