include $(THEOS)/makefiles/common.mk

TWEAK_NAME = LumenSpringBoard
LumenSpringBoard_FILES = LMSpringBoard.x ../Shared/LMThemeLibrary.m
LumenSpringBoard_CFLAGS = -fobjc-arc -Wall -Wno-deprecated-declarations
LumenSpringBoard_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
